# Generated by Django 4.2 on 2023-06-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comemnts',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
