# Generated by Django 4.2 on 2023-06-07 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0002_comemnts_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comemnts',
            new_name='Comemnt',
        ),
    ]
